---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: backend-dummy
spec:
  endpoints:
    - fqdn:
        # Both these values are arbitrary and unused as the PatchPolicy redirects requests.
        hostname: 'foo.bar.com'
        port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: llm-route
spec:
  parentRefs:
  - name: inference-gateway
    sectionName: llm-gw
  rules:
  - backendRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: backend-dummy
    timeouts:
      request: "24h"
      backendRequest: "24h"
