site_name: Learning the GW API Inference extension
site_url: https://eitansuez.github.io/inference-extension-exploration/
repo_url: https://github.com/eitansuez/inference-extension-exploration
theme:
  name: material
  features:
  - content.code.copy
  palette:
    primary: amber
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets:
    base_path:
    - artifacts
- pymdownx.superfences
nav:
- eg.md
- kgateway.md
- kgateway-with-fake-llm.md
