---
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: fakellm-pool
spec:
  targetPortNumber: 8000
  selector:
    app: fake-llm
  extensionRef:
    name: fakellm-pool-endpoint-picker