---
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: qwen-pool
spec:
  targetPortNumber: 8000
  selector:
    app: vllm-qwen-1-5b
  extensionRef:
    name: qwen-pool-endpoint-picker