---
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceModel
metadata:
  name: qwen-inferencemodel
spec:
  modelName: tweet-summary
  criticality: Critical
  poolRef:
    name: qwen-pool
  targetModels:
  - name: tweet-summary-1
    weight: 100
