---
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferenceModel
metadata:
  name: fakellm-inferencemodel
spec:
  modelName: fake-llm
  criticality: Critical
  poolRef:
    name: fakellm-pool
  targetModels:
  - name: fake-llm-lora-a
    weight: 100
